Adds blog post thanking all contributors to PyBR13 campaign
pyladies-brazil/br-pyladies-pelican pull request #211
Opened 2018-03-14 23:41 UTC by letuche

Resolvi inventar moda de diagramar os depoimentos com fotos no meio do post, mas não consegui me entender com os templates então joguei o html dentro do arquivo markdown mesmo. Não consegui testar, é preciso checar como ficou. Alguém ajuda?

2018-03-17 01:30 UTC, darlenedms requested changes

2018-03-17 01:30 UTC, darlenedms commented on content/2018-03-14-agradecimentos-campanha-pybr13.md
> +  float: left;
Não sei exatamente como você pretendia fazer mas acredito que não precisa desse `float: left`.

2018-03-17 01:30 UTC, darlenedms commented on content/2018-03-14-agradecimentos-campanha-pybr13.md
> +  width: 100%;
Pode remover todas essas larguras pro conteúdo ficar da largura do resto da página.

2018-03-17 01:30 UTC, darlenedms commented on content/2018-03-14-agradecimentos-campanha-pybr13.md
> +<body>
Pode remover esse
```
<html>
<head><meta charset="UTF-8"></head>
<body>
```
Pois todo esse conteúdo já ficará dentro dessas tags quando for colocado no template (https://github.com/pyladies-brazil/br-pyladies-pelican/blob/develop/themes/default/templates/article.html#L40)

2018-03-17 01:30 UTC, darlenedms commented on content/2018-03-14-agradecimentos-campanha-pybr13.md
> +    <img src="content/images/gratidao-pybr13/AnaPaulaMendes.jpeg" alt="ana-paula-mendes"/>
Nas imagens, tira esse `content` que deve funcionar. Exemplo:
`<img src="/images/gratidao-pybr13/AnaPaulaMendes.jpeg" alt="ana-paula-mendes"/>`
É importante deixar a barra (`/`) antes de `images` mesmo pra ser relativo. No "build final" (o estático gerado pelo Pelican) não tem essa pasta `content`.

2018-03-17 01:30 UTC, darlenedms commented on content/2018-03-14-agradecimentos-campanha-pybr13.md
> +</html>
Pode remover esse 
```
</body>
</html>
```

2018-03-17 01:30 UTC, darlenedms commented on content/2018-03-14-agradecimentos-campanha-pybr13.md
> +Então, sem mais delongas: muito, muito, muitíssimo obrigada,
Pra lista de contribuidores ficar embaixo do resto do conteúdo, acho que vale colocar uma `div` envolvendo a lista e com um estilo `clear: left` (http://pt-br.learnlayout.com/clear.html).

2018-03-17 01:33 UTC, darlenedms commented
Se as imagens vão ficar pequenas, acho que vale redimensionar/cortar essas maiores pra não carregar imagens grandes desnecessariamente (carregamento mais lento e mais consumo de banda de internet).

2018-03-17 01:50 UTC, darlenedms commented on content/2018-03-14-agradecimentos-campanha-pybr13.md
> +Ademar Peixoto - Biguá<br>
Ao invés de usar `<br>`, cada um deveria estar dentro de uma tag `<p>`, porém você terá que mexer um pouco no CSS porque tem `!important` em vários lugares (https://github.com/pyladies-brazil/br-pyladies-pelican/blob/develop/themes/default/static/css/post.css#L534), então vai precisar tirá-los pra não ficar com um margem enorme.

2018-04-04 01:32 UTC, letuche commented
ping @darlenedms :)

2018-04-07 14:01 UTC, darlenedms commented
@letuche  Percebi que em alguns breakpoints aparece uma linha entre a foto e o depoimento, aparentemente o Foundation coloca uma borda cinza do lado esquerdo da tag `blockquote`. Acho que o ideal seria sobrescrever, mas não é um impeditivo pra subir.

<img width="604" alt="screen shot 2018-04-07 at 10 50 21 am" src="https://user-images.githubusercontent.com/850280/38455674-fe0b34b0-3a51-11e8-8547-00309d48aed4.png">

2018-04-19 19:25 UTC, merged