Update ladies.yml
pyladies-brazil/br-pyladies-pelican pull request #263
Opened 2019-10-05 14:29 UTC by alicemalzac

Me  adicionando como Pyladie

2019-10-05 14:34 UTC, alicemalzac commented
Adicionando o twitter da Pyladies Fortaleza no Site.

2019-10-12 19:39 UTC, jtemporal commented on data/locations.yml
> +  twitter: https://twitter.com/pyladiesfort
```suggestion
```

2019-10-12 19:42 UTC, jtemporal requested changes

2019-10-12 19:42 UTC, jtemporal commented on data/locations.yml
> +  twitter: https://twitter.com/pyladiesfort
@alicemalzac alguem já colocou o twitter do pyladies fortaleza, pode aceitar a sugestao por favor?

2020-02-14 22:37 UTC, jtemporal requested changes

2020-02-14 22:37 UTC, jtemporal commented on data/ladies.yml
> +  image: https://media.licdn.com/dms/image/C4D03AQEmo7OE5mKvtg/profile-displayphoto-shrink_200_200/0?e=1575504000&v=beta&t=GoOzkEjoDBcR4MLJjvx6Ct1D3VeLh0r_saO55ih_3eU
Essa imagem não está disponível, pode ajustar o link para uma imagem válida?

2020-05-15 14:31 UTC, closed without merging