Atualiza cores do site para ficar mais proximo da identidade visual atual
pyladies-brazil/br-pyladies-pelican pull request #375
Opened 2020-08-15 15:07 UTC by biancarosa

**Descrição do PR**
O objetivo desse PR é atualizar o site para a nova identidade visual. Como não sou designer apenas adaptei. Acredito que isso fecha a issue #291.

**Descrição das mudanças**
- Logo no sobre é a atual.
- Logo no topo foi mudada.
- Cores foram para azul (links, bordas, loading)
- Favicons foram atualizados.

**Screenshot**
É melhor ver no preview... naveguem. Sério mesmo.

**Confirmações**
- [x] O PR foi testado localmente
- [x] (se aplicável) Nenhum link está quebrado
- [x] (se aplicável) Nenhuma imagem está quebrada

**Contexto adicional**
N/A

2020-08-15 15:33 UTC, giovana-morais approved these changes
eu gostei, acho que cê mandou benzão! talvez depois possamos de fato repensar o site, mas pra isso precisaríamos de ajuda das designers. :rocket:

2020-08-15 15:37 UTC, giovana-morais requested changes
na real, acabei de ver que a página de blog ficou ainda com a cor anterior. achei que tinha passado por ela, mas tinha esquecido, risos. foi a única coisa que encontrei. 

![Captura de tela de 2020-08-15 12-36-24](https://user-images.githubusercontent.com/12520431/90315717-0118a400-def4-11ea-854b-4046d1bbc9f8.png)

2020-08-16 00:05 UTC, giovana-morais approved these changes

2020-08-16 01:13 UTC, cecivieira commented
Pra mim ainda vejo o blog rosa, na verdade vejo alguns links rosa e o artigo do blog é um deles. Mas, não encontro a cor rosa no código. @giovana-morais no teu local a cor dos links mudou?

2020-08-16 01:14 UTC, cecivieira commented
As animações tão na cor antiga.

![image](https://user-images.githubusercontent.com/30605862/90324342-e66e1b80-df43-11ea-94fe-ad809cf64857.png)

2020-08-16 16:18 UTC, biancarosa commented
Será que não é cache, @cecivieira? Revisando o preview aqui parece que as animações e o blog tão ok: https://deploy-preview-375--pyladies-brasil.netlify.app/

2020-08-16 21:34 UTC, giovana-morais commented
@cecivieira aqui tá tudo azul tbm. nenhum problema nem quando testei pela preview nem quando baixei a branch aqui e vi local.

2020-08-17 11:39 UTC, merged

2020-08-17 11:51 UTC, giovana-morais commented
@cecivieira fiz o merge. vamos avaliar se alguma coisa ainda falta em prod mesmo e aí fazemos uma correção.