Postagem e suporte ao Readme.md
pyladies-brazil/br-pyladies-pelican pull request #431
Opened 2021-04-26 02:47 UTC by pamellabiotec

**Descrição do PR**
Esse PR é resultado de 3 commits: Imagens da postagem, postagem no Blog pela Thayana e Pâmella e suporte no arquivo readme.md. 

**Descrição das mudanças**
E também acrescentei a nota de suporte a seção do Windows no arquivo README.md. 

**Screenshot**
Se aplicável, coloque um print mostrando como suas mudanças aparecem

**Confirmações**
Antes de enviar o Pull Request, faça as seguintes confirmações
- [x] O PR foi testado localmente
- [x] (se aplicável) Nenhum link está quebrado
- [x] (se aplicável) Nenhuma imagem está quebrada

**Contexto adicional**
Adicione aqui qualquer informação que você considera importante ou que as
revisoras devam se atentar no processo de análise.

2021-04-26 11:58 UTC, giovana-morais requested changes

2021-04-26 11:58 UTC, giovana-morais commented on content/2021-04-25-desvendando-o-dna-com-python.md
> +Para a identidade do grupo de bioinformática, criamos algumas bonecas das PyLadies: a primeira com duas traças que remetem a ideia da dupla hélice do DNA com as cores igual ao símbolo da biopython; e
```suggestion
Para a identidade do grupo de bioinformática, criamos algumas bonecas das PyLadies: a primeira com duas tranças que remetem a ideia da dupla hélice do DNA com as cores igual ao símbolo da biopython; e a segunda com a tiara contendo a dupla hélice do DNA que também remete a ideia do símbolo biopython; e a terceira sendo uma versão preta da primeira boneca. 

```

2021-04-26 11:58 UTC, giovana-morais commented on content/2021-04-25-desvendando-o-dna-com-python.md
> +Inicialmente, o grupo no [Slack](https://slackin.pyladies.com/) consistia apenas na divulgação de eventos, cursos, palestras e materiais de estudo na área. Tempo depois, uma das Pyladies, Thayana Tav
```suggestion
Inicialmente, o grupo no [Slack](https://slackin.pyladies.com/) consistia apenas na divulgação de eventos, cursos, palestras e materiais de estudo na área. Tempo depois, uma das PyLadies, Thayana Tavares teve uma ideia: a organização de um grupo de estudos para a resolução de exercícios de bioinformática utilizando o python e a partir da proposição dos desafios apresentados na plataforma da [Rosalind](http://rosalind.info/problems/list-view/).

```

2021-04-26 11:58 UTC, giovana-morais commented on README.md
> +* [Suporte no caso do Windows Home e Single Language](https://github.com/pyladies-brazil/br-pyladies-pelican/issues/430)
tô pensando aqui se seria melhor colocar a documentação da issue aqui pra deixar tudo concentrado em um só documento. que cê acha? @cecivieira pode pitacar aqui?

2021-04-26 18:56 UTC, pamellabiotec commented on README.md
> +* [Suporte no caso do Windows Home e Single Language](https://github.com/pyladies-brazil/br-pyladies-pelican/issues/430)
Por mim, tudo bem. Eu pensei que fosse assim, inicialmente, quando você sugeriu lá na issue.

2021-04-28 13:16 UTC, giovana-morais commented on README.md
> +* [Suporte no caso do Windows Home e Single Language](https://github.com/pyladies-brazil/br-pyladies-pelican/issues/430)
vamos deixar assim por enquanto pra conseguir fazer o merge e publicar a postagem. depois eu vejo com mais calma como ficaria a estrutura do readme (:

2021-04-28 13:17 UTC, giovana-morais approved these changes

2021-04-28 13:17 UTC, merged